version: '2'
services:
  edtool_data:
    image: busybox
    volumes:
      - ./misc/data:/var/lib/mysql
    container_name: edtool_data
  edtool_mysql:
    image: mysql:5.7
    env_file: .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes_from:
      - edtool_data
    volumes:
      - ../application/:/docker-entrypoint-initdb.d/
    container_name: edtool_mysql
  edtooltesting_mysql:
    image: mysql:5.7
    env_file: .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ../application/:/docker-entrypoint-initdb.d/
    container_name: edtooltesting_mysql
  edtool_nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html
    links:
      - edtool_web74
    container_name: edtool_nginx
  edtool_web74:
    build: ./php-fpm74
    volumes:
      - ../:/var/www/html
    links:
      - edtool_mysql
      - edtooltesting_mysql
    env_file: .env
    container_name: edtool_web74

